runtime: python27
entrypoint: custom
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: flaskr.blog
  secure: always

libraries:
- name: ssl
  version: latest
